import { SlideItemProp } from "@/types/SwiperSlides.t";
import { LeagueAssests } from "./leagues";

export const SwiperSlides: SlideItemProp[] = [
  {
    league: "pickpocket",
    levels: [2, 3, 4],
    leagueId: 2,
    upgraded: false,
    imageUrl: LeagueAssests["pickpocket"].casual,
    maxLeagueLevel: 4,
  },
  {
    league: "burglar",
    leagueId: 5,
    upgraded: false,
    imageUrl: LeagueAssests["burglar"].casual,
    levels: [5, 6, 7],
    maxLeagueLevel: 7,
  },
  {
    league: "robber",
    leagueId: 8,
    upgraded: false,
    imageUrl: LeagueAssests["robber"].casual,
    levels: [8, 9, 10],
    maxLeagueLevel: 10,
  },
  {
    league: "bandit",
    leagueId: 11,
    upgraded: false,
    imageUrl: LeagueAssests["bandit"].casual,
    levels: [11, 12, 13],
    maxLeagueLevel: 13,
  },
  {
    league: "swindler",
    leagueId: 14,
    upgraded: false,
    imageUrl: LeagueAssests["swindler"].casual,
    levels: [14, 15, 16],
    maxLeagueLevel: 16,
  },
  {
    league: "masters",
    leagueId: 17,
    upgraded: false,
    imageUrl: LeagueAssests["masters"].casual,
    levels: [17, 18],
    maxLeagueLevel: 18,
  },
  {
    league: "pros",
    leagueId: 19,
    upgraded: false,
    imageUrl: LeagueAssests["pros"].casual,
    levels: [19, 20],
    maxLeagueLevel: 20,
  },
  {
    league: "heisters",
    leagueId: 21,
    upgraded: false,
    imageUrl: LeagueAssests["heisters"].casual,
    levels: [21, 22],
    maxLeagueLevel: 22,
  },
  {
    league: "virtuoso",
    leagueId: 23,
    upgraded: false,
    imageUrl: LeagueAssests["virtuoso"].casual,
    levels: [23, 24],
    maxLeagueLevel: 24,
  },
  {
    league: "legendary",
    leagueId: 25,
    upgraded: false,
    imageUrl: LeagueAssests["legendary"].casual,
    levels: [25, 26],
    maxLeagueLevel: 26,
  },
];
