export const TIERS_STARS: Record<
  number,
  { filledStars: number; isTier: boolean }
> = {
  1: { filledStars: 0, isTier: false },
  2: { filledStars: 1, isTier: false },
  3: { filledStars: 2, isTier: true },
  4: { filledStars: 3, isTier: true },
  5: { filledStars: 1, isTier: false },
  6: { filledStars: 2, isTier: true },
  7: { filledStars: 3, isTier: true },
  8: { filledStars: 1, isTier: false },
  9: { filledStars: 2, isTier: true },
  10: { filledStars: 3, isTier: true },
  11: { filledStars: 1, isTier: false },
  12: { filledStars: 2, isTier: true },
  13: { filledStars: 3, isTier: true },
  14: { filledStars: 1, isTier: false },
  15: { filledStars: 2, isTier: true },
  16: { filledStars: 3, isTier: true },
  17: { filledStars: 1, isTier: false },
  18: { filledStars: 2, isTier: true },
  19: { filledStars: 1, isTier: false },
  20: { filledStars: 2, isTier: true },
  21: { filledStars: 1, isTier: false },
  22: { filledStars: 2, isTier: true },
  23: { filledStars: 1, isTier: false },
  24: { filledStars: 2, isTier: true },
  25: { filledStars: 1, isTier: false },
  26: { filledStars: 2, isTier: true },
};
