const ROB_NOTIFICATION = "rob-notifications";
const VAULT_NOTIFICATION = "vault-notification";
const PAID_LEAGUE_START = 17;
const FREE_LEAGUES_END = 16;
const MIN_WITHDRAW_AMOUNT = 1_000_000;
const LEAST_LEAGUE_ID_FOR_VAULT_STATUS = 2;

const VAULT_LOW_THRESHOLD = 10;
const VAULT_DOWNGRADED_THRESHOLD = 5;

const X_SECRET_PASSWORD_HEADER =
  "QAqme3ZwWQPOBR9eKn8Mj0wv6KaLWvPHkv1o6n9e9y1jrBjU59";

const MINIMUM_DEVICE_WIDTH = 312;

export {
  ROB_NOTIFICATION,
  PAID_LEAGUE_START,
  MIN_WITHDRAW_AMOUNT,
  FREE_LEAGUES_END,
  X_SECRET_PASSWORD_HEADER,
  VAULT_NOTIFICATION,
  VAULT_LOW_THRESHOLD,
  VAULT_DOWNGRADED_THRESHOLD,
  LEAST_LEAGUE_ID_FOR_VAULT_STATUS,
  MINIMUM_DEVICE_WIDTH
};
