export type CurrentModalType =
  | "loot-in-pockets"
  | "loot-in-vault"
  | "stamina"
  | "alarm"
  | "stash"
  | "invite-and-earn"
  | "fake-id"
  | "improved-alarm"
  | "decoy"
  | "reinforcement-vault"
  | "snack"
  | "crowbar"
  | "guard-dog"
  | "huge-bag"
  | "top-up-stash"
  | "profile-info"
  | "pockets-full"
  | "sneaky"
  | "sloppy"
  | "crafty"
  | "vigilant"
  | "cautious"
  | "sleepy"
  | "wanted"
  | "rich"
  | "info";

export type MoreInfoModalType =
  | "stash"
  | "loot-in-pockets"
  | "invite-and-earn"
  | null;
